apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/sample-app-deployment/
    repoURL: https://github.com/Jake-Qu/learndevops.git
  syncPolicy:
    automated: {}
